spring:
  cassandra:
    schema-action: create_if_not_exists

    request:
      timeout: 10s

    connection:
      connect-timeout: 10s

    keyspace-name: "test"
    port: 9042
    contact-points: 127.0.0.1
    local-datacenter: "datacenter1"